-- PREDIIT security hardening
--
-- Keeps the admin access-code experience, but replaces client-side trust with
-- short-lived, opaque server sessions. It also limits user-writable columns,
-- protects private uploads, and makes paid prediction writes atomic.

create extension if not exists pgcrypto;

alter table public.app_secrets
  add column if not exists admin_access_code_hash text;

drop policy if exists "Admins have full access to app_secrets" on public.app_secrets;
revoke all on public.app_secrets from public, anon, authenticated;

do $$
declare
  legacy_code text := '12345';
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'app_secrets'
      and column_name = 'admin_access_code'
  ) then
    execute 'select admin_access_code from public.app_secrets where id = ''global_config'''
      into legacy_code;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'settings'
      and column_name = 'admin_access_code'
  ) then
    execute 'select admin_access_code from public.settings where id = ''global_config'''
      into legacy_code;
  end if;

  insert into public.app_secrets (id, admin_access_code_hash)
  values ('global_config', extensions.crypt(coalesce(legacy_code, '12345'), extensions.gen_salt('bf', 12)))
  on conflict (id) do update
    set admin_access_code_hash = coalesce(
      public.app_secrets.admin_access_code_hash,
      excluded.admin_access_code_hash
    );
end;
$$;

create table if not exists public.admin_sessions (
  id uuid primary key default gen_random_uuid(),
  token_hash bytea not null unique,
  request_fingerprint bytea not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now()
);

create table if not exists public.admin_login_attempts (
  id bigint generated by default as identity primary key,
  request_fingerprint bytea not null,
  attempted_at timestamptz not null default now(),
  succeeded boolean not null default false
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  session_id uuid,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Preserve older audit rows while extending the live table for token-backed
-- sessions. Existing installations used a UUID primary key and extra target
-- columns; neither needs to be rewritten.
alter table public.admin_audit_log
  add column if not exists session_id uuid;
update public.admin_audit_log set details = '{}'::jsonb where details is null;
alter table public.admin_audit_log alter column details set default '{}'::jsonb;
alter table public.admin_audit_log alter column details set not null;
update public.admin_audit_log set created_at = now() where created_at is null;
alter table public.admin_audit_log alter column created_at set default now();
alter table public.admin_audit_log alter column created_at set not null;

alter table public.admin_sessions enable row level security;
alter table public.admin_login_attempts enable row level security;
alter table public.admin_audit_log enable row level security;

revoke all on public.admin_sessions from public, anon, authenticated;
revoke all on public.admin_login_attempts from public, anon, authenticated;
revoke all on public.admin_audit_log from public, anon, authenticated;

-- Remove legacy overloads so no sensitive action remains callable without an
-- opaque admin session token.
drop function if exists public.verify_admin_code(text);
drop function if exists public.check_admin_session();
drop function if exists public.admin_get_all_data();
drop function if exists public.update_diamond_order(uuid, text, text);
drop function if exists public.update_payment_proof(uuid, text, text);
drop function if exists public.admin_update_member_status(uuid, text);
drop function if exists public.admin_approve_booking_code(uuid, text, text, timestamptz);
drop function if exists public.grant_currencies(uuid, integer, integer, integer);
drop function if exists public.admin_update_settings(jsonb);
drop function if exists public.change_admin_access_code(text);
drop function if exists public.get_app_secrets();
drop function if exists public.update_app_secrets(text);
drop function if exists public.admin_get_payment_proof_url(uuid);
drop function if exists public.admin_get_order_proof_url(uuid);
drop function if exists public.admin_delete_record(text, uuid);
drop function if exists public.log_admin_action(text);
drop function if exists public.submit_prediction(uuid, jsonb, integer);
drop function if exists public.admin_add_prediction(uuid, jsonb);
drop function if exists public.admin_delete_prediction(uuid);
drop function if exists public.admin_insert_prediction(jsonb);
drop function if exists public.admin_send_notification(uuid, text, text, text);
drop function if exists public.approve_gold_order(uuid, text, text);
drop function if exists public.get_app_secrets(text);
drop function if exists public.update_app_secrets(text, text);
drop function if exists public.log_admin_action(text, uuid, text, jsonb);
drop function if exists public.update_member_status(uuid, text);
drop function if exists public.get_gold_transactions();

create or replace function public.admin_request_fingerprint()
returns bytea
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  headers jsonb := '{}'::jsonb;
  source_text text;
begin
  begin
    headers := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
  exception when others then
    headers := '{}'::jsonb;
  end;

  source_text := concat_ws('|',
    coalesce(headers->>'x-forwarded-for', headers->>'cf-connecting-ip', 'unknown'),
    coalesce(headers->>'user-agent', 'unknown')
  );
  return extensions.digest(source_text, 'sha256');
end;
$$;

create or replace function public.require_admin_session(p_admin_token uuid)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  session_id uuid;
begin
  if p_admin_token is null then
    raise exception 'Admin session required' using errcode = '28000';
  end if;

  select s.id
  into session_id
  from public.admin_sessions s
  where s.token_hash = extensions.digest(p_admin_token::text, 'sha256')
    and s.expires_at > now()
    and s.request_fingerprint = public.admin_request_fingerprint();

  if session_id is null then
    raise exception 'Admin session expired or invalid' using errcode = '28000';
  end if;

  update public.admin_sessions
  set last_seen_at = now()
  where id = session_id;

  return session_id;
end;
$$;

create or replace function public.verify_admin_code(
  p_code text,
  p_admin_token uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  fingerprint bytea := public.admin_request_fingerprint();
  stored_hash text;
  raw_token uuid;
  expiry timestamptz := now() + interval '30 minutes';
  recent_failures integer;
begin
  delete from public.admin_login_attempts
  where attempted_at < now() - interval '24 hours';
  delete from public.admin_sessions where expires_at <= now();

  select count(*)::integer
  into recent_failures
  from public.admin_login_attempts
  where request_fingerprint = fingerprint
    and succeeded = false
    and attempted_at > now() - interval '15 minutes';

  if recent_failures >= 8 then
    raise exception 'Too many attempts. Try again in 15 minutes.' using errcode = 'P0001';
  end if;

  select admin_access_code_hash
  into stored_hash
  from public.app_secrets
  where id = 'global_config';

  if stored_hash is null or extensions.crypt(coalesce(p_code, ''), stored_hash) <> stored_hash then
    insert into public.admin_login_attempts (request_fingerprint, succeeded)
    values (fingerprint, false);
    return jsonb_build_object('ok', false);
  end if;

  insert into public.admin_login_attempts (request_fingerprint, succeeded)
  values (fingerprint, true);
  delete from public.admin_login_attempts
  where request_fingerprint = fingerprint and succeeded = false;

  raw_token := gen_random_uuid();
  insert into public.admin_sessions (token_hash, request_fingerprint, expires_at)
  values (extensions.digest(raw_token::text, 'sha256'), fingerprint, expiry);

  return jsonb_build_object(
    'ok', true,
    'token', raw_token,
    'expiresAt', (extract(epoch from expiry) * 1000)::bigint
  );
end;
$$;

create or replace function public.check_admin_session(p_admin_token uuid default null)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.require_admin_session(p_admin_token);
  return jsonb_build_object('unlocked', true);
exception when others then
  return jsonb_build_object('unlocked', false);
end;
$$;

create or replace function public.admin_logout(p_admin_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  delete from public.admin_sessions
  where token_hash = extensions.digest(p_admin_token::text, 'sha256');
  return jsonb_build_object('ok', true);
end;
$$;

-- Used only by trusted Edge Functions that must create private Storage URLs.
-- The browser-facing RPCs use require_admin_session(), which also binds the
-- token to the original request fingerprint.
create or replace function public.admin_validate_edge_session(p_admin_token uuid)
returns boolean
language sql
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.admin_sessions
    where token_hash = extensions.digest(p_admin_token::text, 'sha256')
      and expires_at > now()
  );
$$;

-- Users can update their contact details, never balances, status, or role.
revoke insert, update, delete on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
grant insert (id, full_name, email, phone, referral_code) on public.profiles to authenticated;
grant update (full_name, phone, referral_code) on public.profiles to authenticated;

drop policy if exists "Users can update own profile fields" on public.profiles;
create policy "Users can update own safe profile fields"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- Read receipts are the only user-writable notification field.
revoke update on public.notifications from authenticated;
grant update (read_at) on public.notifications to authenticated;
drop policy if exists "Users can update own notifications" on public.notifications;
create policy "Users can mark own notifications read"
on public.notifications for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

grant delete on public.notifications to authenticated;
drop policy if exists "Users can delete own notifications" on public.notifications;
create policy "Users can delete own notifications"
on public.notifications for delete
to authenticated
using (auth.uid() = user_id);

-- Writes that affect money or generated results must use validated RPCs.
revoke insert, update, delete on public.transactions from authenticated;
revoke insert, update on public.predictions from authenticated;
grant delete on public.predictions to authenticated;
drop policy if exists "Users can delete own predictions" on public.predictions;
create policy "Users can delete own predictions"
on public.predictions for delete
to authenticated
using (auth.uid() = user_id);
revoke insert, update, delete on public.ticket_transactions from authenticated;
revoke insert, update on public.spin_signals from authenticated;
revoke insert, update on public.booking_code_requests from authenticated;
revoke insert, update on public.payments from authenticated;
revoke insert, update on public.orders from authenticated;

alter table public.orders add column if not exists asset_type text not null default 'diamonds';
alter table public.orders drop constraint if exists orders_asset_type_check;
alter table public.orders add constraint orders_asset_type_check
  check (asset_type in ('diamonds', 'gold', 'tickets'));

create or replace function public.submit_registration_payment(
  p_country text,
  p_method text,
  p_amount numeric,
  p_currency text,
  p_sender_name text,
  p_sender_number text,
  p_txn_id text,
  p_screenshot_path text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  user_record auth.users%rowtype;
  expected_amount numeric;
  expected_currency text;
  payment_record public.payments%rowtype;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if p_country not in ('GH', 'NG') then raise exception 'Invalid country'; end if;
  if p_screenshot_path not like auth.uid()::text || '/%' then raise exception 'Invalid proof path'; end if;
  if length(trim(p_sender_name)) < 2 or length(trim(p_sender_number)) < 6 then raise exception 'Sender details are required'; end if;

  select * into user_record from auth.users where id = auth.uid();
  select case when p_country = 'GH' then registration_ghs else registration_ngn end
  into expected_amount from public.settings where id = 'global_config';
  expected_currency := case when p_country = 'GH' then 'GHS' else 'NGN' end;
  if p_currency <> expected_currency or p_amount <> expected_amount then raise exception 'Payment amount does not match current registration price'; end if;
  if nullif(trim(p_txn_id), '') is not null and exists (
    select 1 from public.payments where user_id = auth.uid() and txn_id = trim(p_txn_id)
  ) then raise exception 'This transaction has already been submitted'; end if;

  insert into public.payments (
    user_id, email, country, method, amount, currency, sender_name,
    sender_number, txn_id, screenshot_path, status
  ) values (
    auth.uid(), user_record.email, p_country, left(trim(p_method), 80), expected_amount,
    expected_currency, left(trim(p_sender_name), 100), left(trim(p_sender_number), 30),
    nullif(left(trim(p_txn_id), 80), ''), p_screenshot_path, 'pending'
  ) returning * into payment_record;

  return jsonb_build_object('ok', true, 'payment', to_jsonb(payment_record));
end;
$$;

create or replace function public.submit_gold_order(
  p_package_name text,
  p_gold integer,
  p_amount numeric,
  p_currency text,
  p_method text,
  p_txn_id text,
  p_sender_name text,
  p_sender_number text,
  p_screenshot_path text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  user_record auth.users%rowtype;
  expected_amount numeric;
  asset text;
  order_record public.orders%rowtype;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if p_gold not in (5, 15, 30) then raise exception 'Invalid package quantity'; end if;
  if p_currency not in ('GHS', 'NGN') then raise exception 'Invalid currency'; end if;
  expected_amount := case
    when p_currency = 'GHS' and p_gold = 5 then 50
    when p_currency = 'GHS' and p_gold = 15 then 120
    when p_currency = 'GHS' and p_gold = 30 then 200
    when p_currency = 'NGN' and p_gold = 5 then 5000
    when p_currency = 'NGN' and p_gold = 15 then 12000
    when p_currency = 'NGN' and p_gold = 30 then 20000
  end;
  if expected_amount is null or p_amount <> expected_amount then raise exception 'Order amount does not match package'; end if;
  if p_screenshot_path not like auth.uid()::text || '/%' then raise exception 'Invalid proof path'; end if;
  if length(trim(p_sender_name)) < 2 or length(trim(p_sender_number)) < 6 then raise exception 'Sender details are required'; end if;
  if nullif(trim(p_txn_id), '') is not null and exists (
    select 1 from public.orders where user_id = auth.uid() and txn_id = trim(p_txn_id)
  ) then raise exception 'This transaction has already been submitted'; end if;

  asset := case
    when lower(p_package_name) like '%gold%' then 'gold'
    when lower(p_package_name) like '%ticket%' then 'tickets'
    else 'diamonds'
  end;
  select * into user_record from auth.users where id = auth.uid();
  insert into public.orders (
    user_id, email, package_name, diamonds, asset_type, amount, currency,
    method, txn_id, screenshot_path, status
  ) values (
    auth.uid(), user_record.email, left(trim(p_package_name), 100), p_gold, asset,
    expected_amount, p_currency, left(trim(p_method), 80),
    nullif(left(trim(p_txn_id), 80), ''), p_screenshot_path, 'pending'
  ) returning * into order_record;
  return jsonb_build_object('ok', true, 'order', to_jsonb(order_record));
end;
$$;

-- Private proof uploads: owners may upload/read only within their UUID folder.
drop policy if exists "Users upload own payment proofs" on storage.objects;
create policy "Users upload own payment proofs"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'payment-proofs'
  and (storage.foldername(name))[1] = auth.uid()::text
  and lower(storage.extension(name)) in ('jpg', 'jpeg', 'png', 'webp')
  and coalesce((metadata->>'size')::bigint, 0) between 1 and 8388608
);

drop policy if exists "Users read own payment proofs" on storage.objects;
create policy "Users read own payment proofs"
on storage.objects for select
to authenticated
using (
  bucket_id = 'payment-proofs'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users upload own order proofs" on storage.objects;
create policy "Users upload own order proofs"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'screenshot-proofs'
  and (storage.foldername(name))[1] = auth.uid()::text
  and lower(storage.extension(name)) in ('jpg', 'jpeg', 'png', 'webp')
  and coalesce((metadata->>'size')::bigint, 0) between 1 and 8388608
);

drop policy if exists "Users read own order proofs" on storage.objects;
create policy "Users read own order proofs"
on storage.objects for select
to authenticated
using (
  bucket_id = 'screenshot-proofs'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- Atomic prediction charge + ledger + prediction record.
create or replace function public.submit_prediction(
  p_result jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  user_id uuid := auth.uid();
  profile_record public.profiles%rowtype;
  charge integer;
  prediction_id uuid;
begin
  if user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;
  if p_result is null or jsonb_typeof(p_result->'matches') <> 'array'
     or jsonb_array_length(p_result->'matches') = 0 then
    raise exception 'At least one prediction match is required';
  end if;

  select * into profile_record
  from public.profiles
  where id = user_id
  for update;

  if profile_record.status <> 'active' then
    return jsonb_build_object('ok', false, 'reason', 'inactive');
  end if;

  select prediction_cost into charge
  from public.settings where id = 'global_config';
  charge := greatest(coalesce(charge, 50), 0);

  if profile_record.diamonds < charge then
    return jsonb_build_object('ok', false, 'reason', 'diamonds');
  end if;

  update public.profiles
  set diamonds = diamonds - charge
  where id = user_id;

  insert into public.transactions (user_id, kind, amount, reason, balance_after)
  values (user_id, 'debit', charge, 'Prediction analysis', profile_record.diamonds - charge);

  insert into public.predictions (user_id, cost, result)
  values (user_id, charge, p_result)
  returning id into prediction_id;

  return jsonb_build_object(
    'ok', true,
    'predictionId', prediction_id,
    'balanceAfter', profile_record.diamonds - charge,
    'cost', charge
  );
end;
$$;

-- Lock balances during the other debit operations as well.
create or replace function public.request_booking_code()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  profile_record public.profiles%rowtype;
  charge integer;
  request_record public.booking_code_requests%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  select * into profile_record from public.profiles
  where id = auth.uid() for update;
  if profile_record.status <> 'active' then
    return jsonb_build_object('ok', false, 'reason', 'status');
  end if;

  select efootball_cost into charge from public.settings where id = 'global_config';
  charge := greatest(coalesce(charge, 1), 0);
  if profile_record.tickets < charge then
    return jsonb_build_object('ok', false, 'reason', 'tickets');
  end if;

  update public.profiles set tickets = tickets - charge where id = auth.uid();
  insert into public.ticket_transactions (user_id, kind, amount, reason, balance_after)
  values (auth.uid(), 'debit', charge, 'Booking code request', profile_record.tickets - charge);
  insert into public.booking_code_requests (user_id, status, cost)
  values (auth.uid(), 'pending', charge) returning * into request_record;

  return jsonb_build_object('ok', true, 'request', to_jsonb(request_record));
end;
$$;

create or replace function public.reveal_spin_signal()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  profile_record public.profiles%rowtype;
  charge integer;
  signal_record public.spin_signals%rowtype;
  signal_direction text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  select * into profile_record from public.profiles
  where id = auth.uid() for update;
  if profile_record.status <> 'active' then
    return jsonb_build_object('ok', false, 'reason', 'status');
  end if;

  select spin_cost into charge from public.settings where id = 'global_config';
  charge := greatest(coalesce(charge, 50), 0);
  if profile_record.gold < charge then
    return jsonb_build_object('ok', false, 'reason', 'gold');
  end if;

  signal_direction := case when random() > 0.5 then 'up' else 'down' end;
  update public.profiles set gold = gold - charge where id = auth.uid();
  insert into public.transactions (user_id, kind, amount, reason, balance_after)
  values (auth.uid(), 'debit', charge, 'Spin reveal charge', profile_record.gold - charge);
  insert into public.spin_signals (user_id, direction, confidence, round_id, cost)
  values (
    auth.uid(), signal_direction, floor(random() * 30 + 70)::integer,
    'ROUND-' || upper(substring(gen_random_uuid()::text from 1 for 8)), charge
  ) returning * into signal_record;

  return jsonb_build_object('ok', true, 'signal', to_jsonb(signal_record));
end;
$$;

create or replace function public.admin_get_all_data(p_admin_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  config public.settings%rowtype;
begin
  perform public.require_admin_session(p_admin_token);
  select * into config from public.settings where id = 'global_config';

  return jsonb_build_object(
    'members', (select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc), '[]'::jsonb) from public.profiles x),
    'payments', (select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc), '[]'::jsonb) from public.payments x),
    'diamondOrders', (select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc), '[]'::jsonb) from public.orders x),
    'predictions', (select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc), '[]'::jsonb) from public.predictions x),
    'efootball', (select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc), '[]'::jsonb) from public.booking_code_requests x),
    'ticketTransactions', (select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc), '[]'::jsonb) from public.ticket_transactions x),
    'spinSignals', (select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc), '[]'::jsonb) from public.spin_signals x),
    'goldTransactions', (select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc), '[]'::jsonb) from public.transactions x),
    'settings', to_jsonb(config),
    'pricing', jsonb_build_object(
      'prediction_cost', config.prediction_cost,
      'efootball_cost', config.efootball_cost,
      'efootball_expiry', config.efootball_expiry,
      'spin_cost', config.spin_cost,
      'registration_ghs', config.registration_ghs,
      'registration_ngn', config.registration_ngn
    ),
    'paymentSettings', jsonb_build_object(
      'payment_ghana', config.payment_ghana,
      'payment_nigeria', config.payment_nigeria
    ),
    'earnings', jsonb_build_object(
      'totalGHS', coalesce((select sum(amount) from public.payments where status = 'approved' and currency = 'GHS'), 0),
      'totalNGN', coalesce((select sum(amount) from public.payments where status = 'approved' and currency = 'NGN'), 0),
      'payments', '[]'::jsonb,
      'orders', '[]'::jsonb,
      'ticketTransactions', '[]'::jsonb,
      'spinSignals', '[]'::jsonb
    ),
    'stats', jsonb_build_object(
      'revenue', jsonb_build_object(
        'GHS', coalesce((select sum(amount) from public.payments where status = 'approved' and currency = 'GHS'), 0),
        'NGN', coalesce((select sum(amount) from public.payments where status = 'approved' and currency = 'NGN'), 0)
      ),
      'pending', (select count(*) from public.payments where status = 'pending'),
      'members', (select count(*) from public.profiles)
    )
  );
end;
$$;

create or replace function public.update_diamond_order(
  p_order_id uuid,
  p_status text,
  p_note text,
  p_admin_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  order_record public.orders%rowtype;
  current_balance integer;
begin
  perform public.require_admin_session(p_admin_token);
  if p_status not in ('approved', 'rejected') then raise exception 'Invalid status'; end if;

  select * into order_record from public.orders where id = p_order_id for update;
  if order_record.id is null then raise exception 'Order not found'; end if;
  if order_record.status <> 'pending' then
    return jsonb_build_object('ok', false, 'reason', 'Already processed');
  end if;

  update public.orders set status = p_status, admin_note = p_note, reviewed_at = now()
  where id = p_order_id;

  if p_status = 'approved' then
    if order_record.asset_type = 'gold' then
      update public.profiles set gold = gold + order_record.diamonds
      where id = order_record.user_id returning gold into current_balance;
      insert into public.transactions (user_id, kind, amount, reason, balance_after)
      values (order_record.user_id, 'credit', order_record.diamonds, 'Gold package purchase', current_balance);
    elsif order_record.asset_type = 'tickets' then
      update public.profiles set tickets = tickets + order_record.diamonds
      where id = order_record.user_id returning tickets into current_balance;
      insert into public.ticket_transactions (user_id, kind, amount, reason, balance_after)
      values (order_record.user_id, 'credit', order_record.diamonds, 'Ticket package purchase', current_balance);
    else
      update public.profiles set diamonds = diamonds + order_record.diamonds
      where id = order_record.user_id returning diamonds into current_balance;
      insert into public.transactions (user_id, kind, amount, reason, balance_after)
      values (order_record.user_id, 'credit', order_record.diamonds, 'Diamond package purchase', current_balance);
    end if;
  end if;

  insert into public.notifications (user_id, title, body, kind)
  values (
    order_record.user_id,
    case when p_status = 'approved' then 'Package credited' else 'Order declined' end,
    case when p_status = 'approved' then 'Your package has been approved.' else coalesce(p_note, 'Your order was declined.') end,
    case when p_status = 'approved' then 'success' else 'error' end
  );
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.update_payment_proof(
  p_payment_id uuid,
  p_status text,
  p_note text,
  p_admin_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  payment_record public.payments%rowtype;
begin
  perform public.require_admin_session(p_admin_token);
  if p_status not in ('approved', 'rejected') then raise exception 'Invalid status'; end if;

  select * into payment_record from public.payments where id = p_payment_id for update;
  if payment_record.id is null then raise exception 'Payment not found'; end if;
  if payment_record.status <> 'pending' then
    return jsonb_build_object('ok', false, 'reason', 'Already processed');
  end if;

  update public.payments set status = p_status, admin_note = p_note, reviewed_at = now()
  where id = p_payment_id;
  update public.profiles
  set status = case when p_status = 'approved' then 'active' else 'pending' end
  where id = payment_record.user_id;
  insert into public.notifications (user_id, title, body, kind)
  values (
    payment_record.user_id,
    case when p_status = 'approved' then 'Account activated' else 'Payment declined' end,
    case when p_status = 'approved' then 'Your payment was approved and your account is active.' else coalesce(p_note, 'Your payment proof was declined.') end,
    case when p_status = 'approved' then 'success' else 'error' end
  );
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.admin_update_member_status(
  p_user_id uuid,
  p_status text,
  p_admin_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.require_admin_session(p_admin_token);
  if p_status not in ('pending', 'active', 'suspended') then raise exception 'Invalid status'; end if;
  update public.profiles set status = p_status where id = p_user_id;
  return jsonb_build_object('ok', found);
end;
$$;

create or replace function public.admin_approve_booking_code(
  p_request_id uuid,
  p_code text,
  p_market text,
  p_stake_time timestamptz,
  p_admin_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.require_admin_session(p_admin_token);
  update public.booking_code_requests
  set code = upper(trim(p_code)), market = trim(p_market), stake_time = p_stake_time, status = 'approved'
  where id = p_request_id and status = 'pending';
  return jsonb_build_object('ok', found);
end;
$$;

create or replace function public.grant_currencies(
  p_user_id uuid,
  p_diamonds integer default 0,
  p_gold integer default 0,
  p_tickets integer default 0,
  p_admin_token uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  updated_profile public.profiles%rowtype;
begin
  perform public.require_admin_session(p_admin_token);
  if least(p_diamonds, p_gold, p_tickets) < 0 then raise exception 'Negative grants are not allowed'; end if;
  update public.profiles
  set diamonds = diamonds + p_diamonds, gold = gold + p_gold, tickets = tickets + p_tickets
  where id = p_user_id returning * into updated_profile;
  if updated_profile.id is null then raise exception 'Member not found'; end if;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.admin_update_settings(
  p_settings jsonb,
  p_admin_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.require_admin_session(p_admin_token);
  update public.settings set
    payment_ghana = coalesce(p_settings->'payment_ghana', payment_ghana),
    payment_nigeria = coalesce(p_settings->'payment_nigeria', payment_nigeria),
    registration_ghs = coalesce((p_settings->>'registration_ghs')::numeric, registration_ghs),
    registration_ngn = coalesce((p_settings->>'registration_ngn')::numeric, registration_ngn),
    prediction_cost = coalesce((p_settings->>'prediction_cost')::integer, prediction_cost),
    efootball_cost = coalesce((p_settings->>'efootball_cost')::integer, efootball_cost),
    efootball_expiry = coalesce((p_settings->>'efootball_expiry')::integer, efootball_expiry),
    spin_cost = coalesce((p_settings->>'spin_cost')::integer, spin_cost),
    updated_at = now()
  where id = 'global_config';
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.change_admin_access_code(
  p_new_code text,
  p_admin_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  active_session uuid;
begin
  active_session := public.require_admin_session(p_admin_token);
  if length(coalesce(p_new_code, '')) < 6 then raise exception 'Passcode must be at least 6 characters'; end if;
  update public.app_secrets
  set admin_access_code_hash = extensions.crypt(p_new_code, extensions.gen_salt('bf', 12)), updated_at = now()
  where id = 'global_config';
  delete from public.admin_sessions where id <> active_session;
  insert into public.admin_audit_log (session_id, action) values (active_session, 'access_code_changed');
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.get_app_secrets(p_admin_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.require_admin_session(p_admin_token);
  return jsonb_build_object(
    'gemini_api_key', null,
    'gemini_api_key_configured', exists(
      select 1 from public.app_secrets where id = 'global_config' and nullif(gemini_api_key, '') is not null
    )
  );
end;
$$;

create or replace function public.update_app_secrets(
  p_gemini_api_key text,
  p_admin_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.require_admin_session(p_admin_token);
  update public.app_secrets
  set gemini_api_key = nullif(trim(p_gemini_api_key), ''), updated_at = now()
  where id = 'global_config';
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.admin_get_payment_proof_path(
  p_payment_id uuid,
  p_admin_token uuid
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.require_admin_session(p_admin_token);
  return (select screenshot_path from public.payments where id = p_payment_id);
end;
$$;

create or replace function public.admin_get_order_proof_path(
  p_order_id uuid,
  p_admin_token uuid
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.require_admin_session(p_admin_token);
  return (select screenshot_path from public.orders where id = p_order_id);
end;
$$;

create or replace function public.admin_delete_record(
  p_table text,
  p_id uuid,
  p_admin_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.require_admin_session(p_admin_token);
  if p_table = 'profiles' then
    delete from auth.users where id = p_id;
  elsif p_table in ('predictions', 'booking_code_requests', 'payments', 'orders') then
    execute format('delete from public.%I where id = $1', p_table) using p_id;
  else
    raise exception 'Invalid table';
  end if;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.log_admin_action(
  p_action text,
  p_admin_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  session_id uuid;
begin
  session_id := public.require_admin_session(p_admin_token);
  insert into public.admin_audit_log (session_id, action) values (session_id, left(p_action, 120));
  return jsonb_build_object('ok', true);
end;
$$;

-- Remove legacy plaintext access code and browser-readable key helpers.
drop function if exists public.get_gemini_key();
alter table public.settings drop column if exists admin_access_code;
alter table public.app_secrets drop column if exists admin_access_code;

-- Harden helper routines that predate this migration. The auth trigger retains
-- its existing identity, but it is not directly callable through the API.
alter function public.is_admin() set search_path = public, pg_temp;
alter function public.handle_new_user() set search_path = public, pg_temp;
alter function public.get_public_settings() set search_path = public, pg_temp;
revoke all on function public.is_admin() from public;
revoke all on function public.handle_new_user() from public;
revoke all on function public.get_public_settings() from public;
grant execute on function public.is_admin() to anon, authenticated;
grant execute on function public.get_public_settings() to authenticated;

-- SECURITY DEFINER routines are least-privilege: no implicit PUBLIC access.
revoke all on function public.admin_request_fingerprint() from public;
revoke all on function public.require_admin_session(uuid) from public;
revoke all on function public.verify_admin_code(text, uuid) from public;
revoke all on function public.check_admin_session(uuid) from public;
revoke all on function public.admin_logout(uuid) from public;
revoke all on function public.admin_validate_edge_session(uuid) from public;
revoke all on function public.submit_prediction(jsonb) from public;
revoke all on function public.submit_registration_payment(text, text, numeric, text, text, text, text, text) from public;
revoke all on function public.submit_gold_order(text, integer, numeric, text, text, text, text, text, text) from public;
revoke all on function public.request_booking_code() from public;
revoke all on function public.reveal_spin_signal() from public;
revoke all on function public.admin_get_all_data(uuid) from public;
revoke all on function public.update_diamond_order(uuid, text, text, uuid) from public;
revoke all on function public.update_payment_proof(uuid, text, text, uuid) from public;
revoke all on function public.admin_update_member_status(uuid, text, uuid) from public;
revoke all on function public.admin_approve_booking_code(uuid, text, text, timestamptz, uuid) from public;
revoke all on function public.grant_currencies(uuid, integer, integer, integer, uuid) from public;
revoke all on function public.admin_update_settings(jsonb, uuid) from public;
revoke all on function public.change_admin_access_code(text, uuid) from public;
revoke all on function public.get_app_secrets(uuid) from public;
revoke all on function public.update_app_secrets(text, uuid) from public;
revoke all on function public.admin_get_payment_proof_path(uuid, uuid) from public;
revoke all on function public.admin_get_order_proof_path(uuid, uuid) from public;
revoke all on function public.admin_delete_record(text, uuid, uuid) from public;
revoke all on function public.log_admin_action(text, uuid) from public;

grant execute on function public.verify_admin_code(text, uuid) to anon, authenticated;
grant execute on function public.check_admin_session(uuid) to anon, authenticated;
grant execute on function public.admin_logout(uuid) to anon, authenticated;
grant execute on function public.admin_validate_edge_session(uuid) to service_role;
grant execute on function public.admin_get_all_data(uuid) to anon, authenticated;
grant execute on function public.update_diamond_order(uuid, text, text, uuid) to anon, authenticated;
grant execute on function public.update_payment_proof(uuid, text, text, uuid) to anon, authenticated;
grant execute on function public.admin_update_member_status(uuid, text, uuid) to anon, authenticated;
grant execute on function public.admin_approve_booking_code(uuid, text, text, timestamptz, uuid) to anon, authenticated;
grant execute on function public.grant_currencies(uuid, integer, integer, integer, uuid) to anon, authenticated;
grant execute on function public.admin_update_settings(jsonb, uuid) to anon, authenticated;
grant execute on function public.change_admin_access_code(text, uuid) to anon, authenticated;
grant execute on function public.get_app_secrets(uuid) to anon, authenticated;
grant execute on function public.update_app_secrets(text, uuid) to anon, authenticated;
grant execute on function public.admin_get_payment_proof_path(uuid, uuid) to anon, authenticated;
grant execute on function public.admin_get_order_proof_path(uuid, uuid) to anon, authenticated;
grant execute on function public.admin_delete_record(text, uuid, uuid) to anon, authenticated;
grant execute on function public.log_admin_action(text, uuid) to anon, authenticated;

grant execute on function public.submit_prediction(jsonb) to authenticated;
grant execute on function public.submit_registration_payment(text, text, numeric, text, text, text, text, text) to authenticated;
grant execute on function public.submit_gold_order(text, integer, numeric, text, text, text, text, text, text) to authenticated;
grant execute on function public.request_booking_code() to authenticated;
grant execute on function public.reveal_spin_signal() to authenticated;
